server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend
    static_configs:
      - targets: [localhost]
        labels:
          job: backend
          container: indium-backend
          __path__: /var/lib/docker/containers/0e042f157ac68ab4804eb44f124b644f5cfdbd245916953572ebd8ba97449bb5/0e042f157ac68ab4804eb44f124b644f5cfdbd245916953572ebd8ba97449bb5-json.log
    pipeline_stages:
      - json:
          expressions:
            log: log
      - json:
          source: log
          expressions:
            level: level
            msg: msg
            method: method
            status: status_code
      - labels:
          level: level
      - output:
          source: msg
